**Preparing The Raw Data**

Import decsriptions of data and categories. Note that all of the data is in Spanish

In [1]:
import pandas as pd
raw_data_descriptors_es = pd.read_excel(r"..\raw_data\diccionario_datos_covid19\201128 Descriptores_.xlsx")
raw_data_categories_es_unlinked = pd.read_excel(r"..\raw_data\diccionario_datos_covid19\201128 Catalogos.xlsx",
                                   sheet_name=None)

Lets look at all the data destcriptors

In [2]:
raw_data_descriptors_es

,Nº,NOMBRE DE VARIABLE,DESCRIPCIÓN DE VARIABLE,FORMATO O FUENTE
0,1,FECHA_ACTUALIZACION,"La base de datos se alimenta diariamente, esta...",AAAA-MM-DD
1,2,ID_REGISTRO,Número identificador del caso,TEXTO
2,3,ORIGEN,La vigilancia centinela se realiza a través de...,CATÁLOGO: ORIGEN ...
3,4,SECTOR,Identifica el tipo de institución del Sistema ...,CATÁLOGO: SECTOR ...
4,5,ENTIDAD_UM,Identifica la entidad donde se ubica la unidad...,CATALÓGO: ENTIDADES
5,6,SEXO,Identifica al sexo del paciente.,CATÁLOGO: SEXO
6,7,ENTIDAD_NAC,Identifica la entidad de nacimiento del paciente.,CATALÓGO: ENTIDADES
7,8,ENTIDAD_RES,Identifica la entidad de residencia del paciente.,CATALÓGO: ENTIDADES
8,9,MUNICIPIO_RES,Identifica el municipio de residencia del paci...,CATALÓGO: MUNICIPIOS
9,10,TIPO_PACIENTE,Identifica el tipo de atención que recibió el ...,CATÁLOGO: TIPO_PACIENTE
10,11,FECHA_INGRESO,Identifica la fecha de ingreso del paciente a ...,AAAA-MM-DD
11,12,FECHA_SINTOMAS,Idenitifica la fecha en que inició la sintomat...,AAAA-MM-DD
12,13,FECHA_DEF,Identifica la fecha en que el paciente falleció.,AAAA-MM-DD
13,14,INTUBADO,Identifica si el paciente requirió de intubación.,CATÁLOGO: SI_ NO ...
14,15,NEUMONIA,Identifica si al paciente se le diagnosticó co...,CATÁLOGO: SI_ NO ...
15,16,EDAD,Identifica la edad del paciente.,NÚMERICA EN AÑOS
16,17,NACIONALIDAD,Identifica si el paciente es mexicano o extran...,CATÁLOGO: NACIONALIDAD
17,18,EMBARAZO,Identifica si la paciente está embarazada.,CATÁLOGO: SI_ NO ...
18,19,HABLA_LENGUA_INDIG,Identifica si el paciente habla lengua índigena.,CATÁLOGO: SI_ NO ...
19,20,INDIGENA,Identifica si el paciente se autoidentifica co...,CATÁLOGO: SI_ NO ...
20,21,DIABETES,Identifica si el paciente tiene un diagnóstico...,CATÁLOGO: SI_ NO ...
21,22,EPOC,Identifica si el paciente tiene un diagnóstico...,CATÁLOGO: SI_ NO ...
22,23,ASMA,Identifica si el paciente tiene un diagnóstico...,CATÁLOGO: SI_ NO ...
23,24,INMUSUPR,Identifica si el paciente presenta inmunosupre...,CATÁLOGO: SI_ NO ...
24,25,HIPERTENSION,Identifica si el paciente tiene un diagnóstico...,CATÁLOGO: SI_ NO ...
25,26,OTRAS_COM,Identifica si el paciente tiene diagnóstico de...,CATÁLOGO: SI_ NO ...
26,27,CARDIOVASCULAR,Identifica si el paciente tiene un diagnóstico...,CATÁLOGO: SI_ NO ...
27,28,OBESIDAD,Identifica si el paciente tiene diagnóstico de...,CATÁLOGO: SI_ NO ...
28,29,RENAL_CRONICA,Identifica si el paciente tiene diagnóstico de...,CATÁLOGO: SI_ NO ...
29,30,TABAQUISMO,Identifica si el paciente tiene hábito de taba...,CATÁLOGO: SI_ NO ...
30,31,OTRO_CASO,Identifica si el paciente tuvo contacto con al...,CATÁLOGO: SI_ NO ...
31,32,TOMA_MUESTRA_LAB,Identifica si al paciente se le tomó muestra d...,CATÁLOGO: SI_ NO
32,33,RESULTADO_LAB,Identifica el resultado del análisis de la mue...,CATÁLOGO: RESULTADO_LAB
33,34,TOMA_MUESTRA_ANTIGENO,Identifica si al paciente se le tomó muestra d...,CATÁLOGO: SI_ NO
34,35,RESULTADO_ANTIGENO,Identifica el resultado del análisis de la mue...,CATÁLOGO: RESULTADO_ANTIGENO
35,36,CLASIFICACION_FINAL,Identifica si el paciente es un caso de COVID-...,CATÁLOGO: CLASIFICACION_FINAL
36,37,MIGRANTE,Identifica si el paciente es una persona migra...,CATÁLOGO: SI_ NO ...
37,38,PAIS_NACIONALIDAD,Identifica la nacionalidad del paciente.,"TEXTO, 99= SE IGNORA"
38,39,PAIS_ORIGEN,Identifica el país del que partió el paciente ...,"TEXTO, 97= NO APLICA"
39,40,UCI,Identifica si el paciente requirió ingresar a ...,CATÁLOGO: SI_ NO ...

Let's also look at the data categories and the 
descriptions of what the keys represent

In [3]:
raw_data_categories_es = pd.concat(raw_data_categories_es_unlinked, axis=1, ignore_index = False, sort=False)
raw_data_categories_es

     Catálogo ORIGEN                  Catálogo SECTOR                  \
               CLAVE      DESCRIPCIÓN           CLAVE     DESCRIPCIÓN
0                1.0            USMER             1.0       CRUZ ROJA
1                2.0   FUERA DE USMER             2.0             DIF
2               99.0  NO ESPECIFICADO             3.0         ESTATAL
3                NaN              NaN             4.0            IMSS
4                NaN              NaN             5.0  IMSS-BIENESTAR
...              ...              ...             ...             ...
2496             NaN              NaN             NaN             NaN
2497             NaN              NaN             NaN             NaN
2498             NaN              NaN             NaN             NaN
2499             NaN              NaN             NaN             NaN
2500             NaN              NaN             NaN             NaN

     Catálogo SEXO                  Catálogo TIPO_PACIENTE                   \
             CLAVE      DESCRIPCIÓN                  CLAVE      DESCRIPCIÓN
0              1.0            MUJER                    1.0      AMBULATORIO
1              2.0           HOMBRE                    2.0    HOSPITALIZADO
2             99.0  NO ESPECIFICADO                   99.0  NO ESPECIFICADO
3              NaN              NaN                    NaN              NaN
4              NaN              NaN                    NaN              NaN
...            ...              ...                    ...              ...
2496           NaN              NaN                    NaN              NaN
2497           NaN              NaN                    NaN              NaN
2498           NaN              NaN                    NaN              NaN
2499           NaN              NaN                    NaN              NaN
2500           NaN              NaN                    NaN              NaN

     Catálogo SI_NO                   ...   Catálogo RESULTADO_ANTIGENO  \
              CLAVE      DESCRIPCIÓN  ...                    Unnamed: 1
0               1.0              SI   ...                   DESCRIPCIÓN
1               2.0              NO   ...         POSITIVO A SARS-COV-2
2              97.0        NO APLICA  ...         NEGATIVO A SARS-COV-2
3              98.0        SE IGNORA  ...  NO APLICA (CASO SIN MUESTRA)
4              99.0  NO ESPECIFICADO  ...                           NaN
...             ...              ...  ...                           ...
2496            NaN              NaN  ...                           NaN
2497            NaN              NaN  ...                           NaN
2498            NaN              NaN  ...                           NaN
2499            NaN              NaN  ...                           NaN
2500            NaN              NaN  ...                           NaN

     Catálogo CLASIFICACION_FINAL  \
                       Unnamed: 0
0                             NaN
1                           CLAVE
2                               1
3                               2
4                               3
...                           ...
2496                          NaN
2497                          NaN
2498                          NaN
2499                          NaN
2500                          NaN

                                                         \
                                             Unnamed: 1
0                                                   NaN
1                                         CLASIFICACIÓN
2     CASO DE COVID-19 CONFIRMADO POR ASOCIACIÓN CLÍ...
3     CASO DE COVID-19 CONFIRMADO POR COMITÉ DE  DIC...
4                        CASO DE SARS-COV-2  CONFIRMADO
...                                                 ...
2496                                                NaN
2497                                                NaN
2498                                                NaN
2499                                                NaN
2500                                                NaN

                                                        Catálogo de ENTIDADES  \
                                             Unnamed: 2         CLAVE_ENTIDAD
0                                                   NaN                   1.0
1                                           DESCRIPCIÓN                   2.0
2     Confirmado por asociación aplica cuando el cas...                   3.0
3     Confirmado por dictaminación solo aplica para ...                   4.0
4     Confirmado aplica cuando:\nEl caso tiene muest...                   5.0
...                                                 ...                   ...
2496                                                NaN                   NaN
2497                                                NaN                   NaN
2498                                                NaN                   NaN
2499                                                NaN                   NaN
2500                                                NaN                   NaN

                                       Catálogo MUNICIPIOS                   \
        ENTIDAD_FEDERATIVA ABREVIATURA     CLAVE_MUNICIPIO        MUNICIPIO
0           AGUASCALIENTES          AS                   1   AGUASCALIENTES
1          BAJA CALIFORNIA          BC                   2         ASIENTOS
2      BAJA CALIFORNIA SUR          BS                   3         CALVILLO
3                 CAMPECHE          CC                   4            COSÍO
4     COAHUILA DE ZARAGOZA          CL                   5      JESÚS MARÍA
...                    ...         ...                 ...              ...
2496                   NaN         NaN                 999  NO ESPECIFICADO
2497                   NaN         NaN                 999  NO ESPECIFICADO
2498                   NaN         NaN                 997        NO APLICA
2499                   NaN         NaN                 998        SE IGNORA
2500                   NaN         NaN                 999  NO ESPECIFICADO


     CLAVE_ENTIDAD
0                1
1                1
2                1
3                1
4                1
...            ...
2496            32
2497            36
2498            97
2499            98
2500            99

[2501 rows x 25 columns]

The raw data

In [4]:
raw_data_es = pd.read_csv(r"..\raw_data\datos_abiertos_covid19\201202COVID19MEXICO.csv", encoding = "latin")
raw_data_es

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-12-02,071735,2,9,21,2,21,21,114,1,...,2,1,1,2,97,3,99,MÃ©xico,97,97
1,2020-12-02,1426fb,1,4,10,1,28,10,7,1,...,99,1,1,2,97,3,99,MÃ©xico,97,97
2,2020-12-02,1c4583,2,12,9,2,9,9,4,1,...,2,1,1,2,97,3,99,MÃ©xico,97,97
3,2020-12-02,0d55c9,2,12,9,1,9,9,16,1,...,2,1,1,2,97,3,99,MÃ©xico,97,97
4,2020-12-02,1468a5,1,4,5,1,15,5,18,1,...,1,1,1,2,97,3,99,MÃ©xico,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2919874,2020-12-02,3d77fa,2,12,9,2,9,9,15,1,...,2,2,97,1,2,7,99,MÃ©xico,97,97
2919875,2020-12-02,2e3c7a,2,12,9,2,9,9,7,1,...,1,2,97,1,2,7,99,MÃ©xico,97,97
2919876,2020-12-02,305af6,1,12,26,1,26,26,18,1,...,2,1,3,2,97,6,99,MÃ©xico,97,97
2919877,2020-12-02,346a40,2,4,21,2,21,21,114,1,...,2,1,3,2,97,6,99,MÃ©xico,97,97
2919878,2020-12-02,1e9f5a,2,4,9,2,9,15,58,1,...,2,1,3,2,97,6,99,MÃ©xico,97,97

We now begin the preprocessing. We first select the features we will use. 
We translate these features:
1. Sex
2. Age
3. Pregnancy
4. Indigenous
5. Pneumonia
6. Diabetes
7. COPD (Chronic Obstructive Pulmonary Disorder)
8. Asthma
9. Immunosuppresion 
10. Hypertension
11. Other Conditions
12. Cardiovascular
13. Obesity
14. Chronic Kidney Disease
15. Smoking
16. Final Classification
17. ICU
18. Speaks Indigenous l=Language

We note that we also include the feature "HABLA_LENGUA_INDIG" (Speaks an indigenous language).
This is to later see the discprepency between people who idetify as indigenous and those that speak an indigenous language.

In [5]:
new_index = ["SEXO", 
             "EDAD", 
             "EMBARAZO",
             "INDIGENA",
             "NEUMONIA",
             "DIABETES", 
             "EPOC", 
             "ASMA",
             "INMUSUPR", 
             "HIPERTENSION", 
             "OTRA_COM", 
             "CARDIOVASCULAR",
             "OBESIDAD",
             "RENAL_CRONICA", 
             "TABAQUISMO", 
             "CLASIFICACION_FINAL",
             "UCI",
             "HABLA_LENGUA_INDIG"
            ] 

raw_data_es = raw_data_es.loc[:,new_index] 
raw_data_es

,SEXO,EDAD,EMBARAZO,INDIGENA,NEUMONIA,DIABETES,EPOC,ASMA,INMUSUPR,HIPERTENSION,OTRA_COM,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,CLASIFICACION_FINAL,UCI,HABLA_LENGUA_INDIG
0,2,75,97,2,2,1,2,2,2,2,2,1,2,2,2,3,97,2
1,1,55,2,2,2,1,2,2,2,1,2,2,1,2,2,3,97,2
2,2,23,97,2,2,2,2,2,2,2,2,2,2,2,2,3,97,2
3,1,28,2,2,2,2,2,2,2,2,2,2,2,2,2,3,97,2
4,1,47,2,2,2,2,2,2,2,2,2,2,2,2,2,3,97,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2919874,2,59,97,2,2,2,2,2,2,2,2,2,2,2,2,7,97,2
2919875,2,71,97,2,2,2,2,2,2,2,2,2,2,2,2,7,97,2
2919876,1,59,2,2,2,1,2,2,2,2,2,2,2,2,2,6,97,2
2919877,2,48,97,2,1,2,2,2,2,2,2,2,2,2,2,6,97,2
2919878,2,26,97,2,2,2,2,2,2,2,2,2,2,2,2,6,97,2

Lets look at the Final Classification category. 
This describes 7 posibilities for classifying a case of COVID-19, 
such as how cases were confirmed or invalidated, suspected cases, and negative cases.

In [6]:
raw_data_categories_es["Catálogo CLASIFICACION_FINAL"].iloc[:10,:]

,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,NaN,NaN,NaN
1,CLAVE,CLASIFICACIÓN,DESCRIPCIÓN
2,1,CASO DE COVID-19 CONFIRMADO POR ASOCIACIÓN CLÍ...,Confirmado por asociación aplica cuando el cas...
3,2,CASO DE COVID-19 CONFIRMADO POR COMITÉ DE DIC...,Confirmado por dictaminación solo aplica para ...
4,3,CASO DE SARS-COV-2 CONFIRMADO,Confirmado aplica cuando:\nEl caso tiene muest...
5,4,INVÁLIDO POR LABORATORIO,Inválido aplica cuando el caso no tienen asoci...
6,5,NO REALIZADO POR LABORATORIO,No realizado aplica cuando el caso no tienen a...
7,6,CASO SOSPECHOSO,Sospechoso aplica cuando: \nEl caso no tienen ...
8,7,NEGATIVO A SARS-COV-2,Negativo aplica cuando el caso:\n1. Se le tomo...
9,NaN,NaN,NaN

Here we translate the text. 

Confirmed by association applies when the case reported being a contact with a positive COVID-19 (and this is registered in SISVER) and:
The case was not sampled or the sample was invalid.

Confirmed by ruling only applies to deaths under the following conditions:
The case was not sampled or a sample was taken, but the sample was invalid.

Confirmed applies when:
The case has a laboratory sample or antigenic test and was positive for SARS-CoV-2, regardless of whether the case has a clinical epidemiological association.

Invalid applies when the case does not have a clinical epidemiological association, nor a COVID-19 ruling. A laboratory sample was taken and it was invalid.

Not carried out applies when the case does not have a clinical epidemiological association, or a COVID-19 ruling and a laboratory sample was taken and it was not processed.

Suspect applies when:
The case does not have a clinical epidemiological association, nor is it dictated by COVID-19 and no sample was taken, or a laboratory sample was taken and the result is pending, regardless of another condition.

Negative applies when the case:
1. A laboratory sample was taken and it was: negative for SARS-COV-2 or positive for any other respiratory virus (Influenza, RSV, Bocavirus, others) regardless of whether this case has an epidemiological clinical association or a COVID-19 ruling .
2. An antigenic sample was taken that was negative for SARS-COV-2 and the case was not taken from a laboratory sample or confirmed by epidemiological association or by clinical epidemiological opinion.

In [7]:
for i in range(2,9):
    print(raw_data_categories_es["Catálogo CLASIFICACION_FINAL"].iloc[i,2])
    print()

Confirmado por asociación aplica cuando el caso informó ser contacto de un positivo a COVID-19 (y este se encuentra registrado en el SISVER) y:
Al caso no se le tomo muestra o la muestra resultó no válida.

Confirmado por dictaminación solo aplica para defunciones bajo las siguientes condiciones:
Al caso no se le tomo muestra o sí se tomó muestra, pero la muestra resultó no válida.

Confirmado aplica cuando:
El caso tiene muestra de laboratorio o prueba antigénica y resultó positiva  a SARS-CoV-2, sin importar si el caso tienen asociación clínica epidemiológica.

Inválido aplica cuando el caso no tienen asociación clínico epidemiológica, ni dictaminación a COVID-19. Se le tomó muestra de laboratorio y esta resultó no válida.

No realizado aplica cuando el caso no tienen asociación clínico epidemiológica, ni dictaminación a COVID-19 y se le tomó muestra de laboratorio y esta no se procesó.

Sospechoso aplica cuando:
El caso no tienen asociación clínico epidemiológica, ni dictaminación a COVID-19 y no se le tomó muestra, o se le tomó muestra de laboratorio y está pendiente de resultado, sin importar otra condición.

Negativo aplica cuando el caso:
1. Se le tomo muestra de laboratorio y ésta resultó: negativa a SARS-COV-2 o positiva a cualquier otro virus respiratorio (Influenza, VSR, Bocavirus, otros) sin importar que este caso tenga asociación clínico epidemiológica o dictaminación a COVID-19.
2. Se le tomó muestra antigénica que resultó negativa a SARS-COV-2 y al caso no se le tomó muestra de laboratorio ni se le confirmo por asosiación epidemiológica o por dictaminación clínica epidemiológica.

After reading this we decide for simplicity to take only positive COVID cases confirmed by testing.
This corresponds to key (clave) 3. 

Now we turn our focus to the Indigenous category. This feature is of the SI_NO (Yes_No) category. 
Let's see the description for this category.

In [8]:
raw_data_categories_es["Catálogo SI_NO"].iloc[:6,]

   CLAVE      DESCRIPCIÓN
0    1.0              SI
1    2.0              NO
2   97.0        NO APLICA
3   98.0        SE IGNORA
4   99.0  NO ESPECIFICADO
5    NaN              NaN

We note that 1.0 means Yes and 99.0 means not specified. We now look at the counts for Indigenous 
and Speaks Indigenous Language. There are quite a lot of not specified in both of these categories, so we drop Speaks Indigenous Language for simplicity.

In [9]:
count = raw_data_es.groupby(["INDIGENA", "HABLA_LENGUA_INDIG"]).count()
count

                                SEXO     EDAD  EMBARAZO  NEUMONIA  DIABETES  \
INDIGENA HABLA_LENGUA_INDIG
1        1                     18409    18409     18409     18409     18409
         2                     11802    11802     11802     11802     11802
         99                      209      209       209       209       209
2        1                      3911     3911      3911      3911      3911
         2                   2768192  2768192   2768192   2768192   2768192
         99                     7452     7452      7452      7452      7452
99       1                        85       85        85        85        85
         2                      4330     4330      4330      4330      4330
         99                   105489   105489    105489    105489    105489

                                EPOC     ASMA  INMUSUPR  HIPERTENSION  \
INDIGENA HABLA_LENGUA_INDIG
1        1                     18409    18409     18409         18409
         2                     11802    11802     11802         11802
         99                      209      209       209           209
2        1                      3911     3911      3911          3911
         2                   2768192  2768192   2768192       2768192
         99                     7452     7452      7452          7452
99       1                        85       85        85            85
         2                      4330     4330      4330          4330
         99                   105489   105489    105489        105489

                             OTRA_COM  CARDIOVASCULAR  OBESIDAD  \
INDIGENA HABLA_LENGUA_INDIG
1        1                      18409           18409     18409
         2                      11802           11802     11802
         99                       209             209       209
2        1                       3911            3911      3911
         2                    2768192         2768192   2768192
         99                      7452            7452      7452
99       1                         85              85        85
         2                       4330            4330      4330
         99                    105489          105489    105489

                             RENAL_CRONICA  TABAQUISMO  CLASIFICACION_FINAL  \
INDIGENA HABLA_LENGUA_INDIG
1        1                           18409       18409                18409
         2                           11802       11802                11802
         99                            209         209                  209
2        1                            3911        3911                 3911
         2                         2768192     2768192              2768192
         99                           7452        7452                 7452
99       1                              85          85                   85
         2                            4330        4330                 4330
         99                         105489      105489               105489

                                 UCI
INDIGENA HABLA_LENGUA_INDIG
1        1                     18409
         2                     11802
         99                      209
2        1                      3911
         2                   2768192
         99                     7452
99       1                        85
         2                      4330
         99                   105489

In [10]:
raw_data_es = raw_data_es.drop(columns = ["HABLA_LENGUA_INDIG"], axis =1)
raw_data_es = raw_data_es.reset_index(drop=True)

We now look at the counts for the keys in Indigenous

In [11]:
raw_data_es = raw_data_es[raw_data_es["INDIGENA"] ==1.0]
count = raw_data_es.groupby(["CLASIFICACION_FINAL", "INDIGENA"]).count()
count

,,SEXO,EDAD,EMBARAZO,NEUMONIA,DIABETES,EPOC,ASMA,INMUSUPR,HIPERTENSION,OTRA_COM,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,UCI
CLASIFICACION_FINAL,INDIGENA,,,,,,,,,,,,,,,
1,1,385,385,385,385,385,385,385,385,385,385,385,385,385,385,385
2,1,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
3,1,11433,11433,11433,11433,11433,11433,11433,11433,11433,11433,11433,11433,11433,11433,11433
4,1,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78
5,1,518,518,518,518,518,518,518,518,518,518,518,518,518,518,518
6,1,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390
7,1,13592,13592,13592,13592,13592,13592,13592,13592,13592,13592,13592,13592,13592,13592,13592

We now take as our data those with Indigenous key values of 1 and Final Calssification Vlaues of 3. Since everyone in our this dataset is Indigenous and tested positive for COVID-19, we drop these columns. We also reset the index.

In [12]:
raw_data_es = raw_data_es[(raw_data_es["CLASIFICACION_FINAL"] == 3)]# | (raw_data_es["CLASIFICACION_FINAL"] == 7)]
raw_data_es = raw_data_es.drop(columns = ["INDIGENA", "CLASIFICACION_FINAL"], axis =1)

raw_data_es = raw_data_es.reset_index(drop=True)
raw_data_es

,SEXO,EDAD,EMBARAZO,NEUMONIA,DIABETES,EPOC,ASMA,INMUSUPR,HIPERTENSION,OTRA_COM,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,UCI
0,2,67,97,1,1,2,2,2,1,2,2,1,2,2,2
1,1,27,2,2,2,2,2,2,2,2,2,2,2,2,97
2,1,38,2,1,2,2,2,2,2,2,2,2,2,2,97
3,1,22,2,2,2,2,2,2,2,2,2,2,2,1,97
4,1,32,2,2,2,2,2,2,2,2,2,2,2,1,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11428,1,51,2,2,2,2,2,2,2,2,2,2,2,2,97
11429,2,59,97,2,2,2,2,2,2,2,2,1,2,2,97
11430,1,47,2,2,2,2,2,2,1,2,2,1,2,2,97
11431,2,76,97,1,2,2,2,2,2,2,2,2,2,2,2
11432,2,60,97,2,2,2,2,2,2,2,2,2,2,2,97

Now we rename and translate the columns.

In [13]:
translations = {
    "SEXO": "Sex", 
    "EDAD":"Age",
    "EMBARAZO":"Pregnant",
    "NEUMONIA":"Pneumonia",
    "DIABETES":"Diabetes", 
    "EPOC":"COPD", 
    "ASMA":"Athsma",
    "INMUSUPR":"Immunosuppressed", 
    "HIPERTENSION":"Hypertension", 
    "OTRA_COM":"Other Conds.", 
    "CARDIOVASCULAR":"Cardiovascular",
    "OBESIDAD":"Obesity",
    "RENAL_CRONICA":"Chronic Kidney Disease", 
    "TABAQUISMO":"Smoking",
    "UCI":"ICU"
}
raw_data_es = raw_data_es.rename(columns = translations)
raw_data_es

,Sex,Age,Pregnant,Pneumonia,Diabetes,COPD,Athsma,Immunosuppressed,Hypertension,Other Conds.,Cardiovascular,Obesity,Chronic Kidney Disease,Smoking,ICU
0,2,67,97,1,1,2,2,2,1,2,2,1,2,2,2
1,1,27,2,2,2,2,2,2,2,2,2,2,2,2,97
2,1,38,2,1,2,2,2,2,2,2,2,2,2,2,97
3,1,22,2,2,2,2,2,2,2,2,2,2,2,1,97
4,1,32,2,2,2,2,2,2,2,2,2,2,2,1,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11428,1,51,2,2,2,2,2,2,2,2,2,2,2,2,97
11429,2,59,97,2,2,2,2,2,2,2,2,1,2,2,97
11430,1,47,2,2,2,2,2,2,1,2,2,1,2,2,97
11431,2,76,97,1,2,2,2,2,2,2,2,2,2,2,2
11432,2,60,97,2,2,2,2,2,2,2,2,2,2,2,97

We now prepare to convert our most of our data values from 1 and 2 to 1 and 0, representing yes and no (or female and male).

We note that a value of 97 means not applicable, which we interpret as a 0 (no).
We also note that a value of 98 means to ignore, which we interpret as a 0 (no) for ICU and as NaN otherwise.
We recall that a value of 99 means not specifified, which we interpret as a Nan .

In [14]:
#ICU is a rare event
count = raw_data_es.groupby(["ICU"]).count()
count

,Sex,Age,Pregnant,Pneumonia,Diabetes,COPD,Athsma,Immunosuppressed,Hypertension,Other Conds.,Cardiovascular,Obesity,Chronic Kidney Disease,Smoking
ICU,,,,,,,,,,,,,,
1,338,338,338,338,338,338,338,338,338,338,338,338,338,338
2,3306,3306,3306,3306,3306,3306,3306,3306,3306,3306,3306,3306,3306,3306
97,7780,7780,7780,7780,7780,7780,7780,7780,7780,7780,7780,7780,7780,7780
99,9,9,9,9,9,9,9,9,9,9,9,9,9,9

In [15]:
def re_number(x:int):
    if x ==1.0:
        return 1
    elif x == 99 or x == 98:
        return 
    else:
        return 0
    
    
def re_number_ICU(x:int):
    if x == 1.0:
        return 1
    elif x == 99:
        return 0
    else:
        return 0

# loop to clean up data
for i in range(0,15):
    # skip Age
    if i == 1:
        continue
    raw_data_es.iloc[:,i] = raw_data_es.iloc[:,i].apply(re_number)
    # second application is to clean up data, for some reason we
    # have a mixture of floats and ints otherwise
    raw_data_es.iloc[:,i] = raw_data_es.iloc[:,i].apply(re_number)

raw_data_es["ICU"] = raw_data_es["ICU"].apply(re_number_ICU)

raw_data_es = raw_data_es.dropna(axis=0)
raw_data_es = raw_data_es.reset_index(drop=True)
raw_data_es

,Sex,Age,Pregnant,Pneumonia,Diabetes,COPD,Athsma,Immunosuppressed,Hypertension,Other Conds.,Cardiovascular,Obesity,Chronic Kidney Disease,Smoking,ICU
0,0,67,0,1,1,0,0,0,1,0,0,1,0,0,0
1,1,27,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,38,0,1,0,0,0,0,0,0,0,0,0,0,0
3,1,22,0,0,0,0,0,0,0,0,0,0,0,1,0
4,1,32,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11428,1,51,0,0,0,0,0,0,0,0,0,0,0,0,0
11429,0,59,0,0,0,0,0,0,0,0,0,1,0,0,0
11430,1,47,0,0,0,0,0,0,1,0,0,1,0,0,0
11431,0,76,0,1,0,0,0,0,0,0,0,0,0,0,0
11432,0,60,0,0,0,0,0,0,0,0,0,0,0,0,0

Finally, we export the data into our processed data folder.

In [16]:
raw_data_es.to_csv(r"..\processed_data\Mexico_Indigenous_Covid_Data.csv", index = False)

In [17]:
#Check new ICU counts
count = raw_data_es.groupby(["ICU"]).count()
count

,Sex,Age,Pregnant,Pneumonia,Diabetes,COPD,Athsma,Immunosuppressed,Hypertension,Other Conds.,Cardiovascular,Obesity,Chronic Kidney Disease,Smoking
ICU,,,,,,,,,,,,,,
0,11095,11095,11095,11095,11095,11095,11095,11095,11095,11095,11095,11095,11095,11095
1,338,338,338,338,338,338,338,338,338,338,338,338,338,338